import Head from "next/head";
import Link from "next/link";

export default function Terms() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white p-8">
      <Head>
        <title>Terms & Conditions - 𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋</title>
        <meta name="description" content="Terms & Conditions for SAMKIEL BOT" />
      </Head>
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-bold mb-8">
          Terms & Conditions
        </h1>
        <div className="prose dark:prose-invert max-w-none">
          <p className="mb-4">Welcome to 𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋.</p>
          <p className="mb-4">
            By using this platform or deploying any bot instance, you agree to
            the following terms:
          </p>
          <ol className="list-decimal list-inside mb-6 space-y-2">
            <li>
              You are solely responsible for how you use the bot and all
              activity generated by your deployment.
            </li>
            <li>
              𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋 is not affiliated with or endorsed by WhatsApp Inc.
            </li>
            <li>
              Excessive or automated bot usage may lead to your WhatsApp account
              being temporarily or permanently banned.
            </li>
            <li>
              Samkiel Bot, its developers, and management are not responsible
              for any bans, suspensions, or damages caused by misuse.
            </li>
            <li>
              Do not use the bot for spam, harassment, illegal activity, or any
              action that violates WhatsApp's terms of service.
            </li>
            <li>
              These terms may be updated periodically. Continued use of this
              service means you agree to any future updates.
            </li>
          </ol>
          <p className="mb-8">
            By continuing to use the platform, you confirm that you understand
            and accept these conditions.
          </p>
        </div>
        <Link
          href="/"
          className="text-blue-500 dark:text-blue-400 hover:underline transition-colors"
        >
          Back to Home
        </Link>
      </div>
    </div>
  );
}
